import type { Metadata } from "next";
import { notoSans } from "@/app/font/font";
import "./globals.css";
import { Menu } from "@/app/parts/menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${notoSans.className} antialiased`}>
          <Menu/>
          <main className="flex">
            <div className="w-52"/>
            {children}
          </main>
      </body>
    </html>
  );
}
